# Form implementation generated from reading ui file '.\net_config_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NetConfigDialog(object):
    def setupUi(self, NetConfigDialog):
        NetConfigDialog.setObjectName("NetConfigDialog")
        NetConfigDialog.resize(400, 98)
        NetConfigDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(NetConfigDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.cbAddress = QtWidgets.QComboBox(parent=NetConfigDialog)
        self.cbAddress.setObjectName("cbAddress")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbAddress)
        self.label = QtWidgets.QLabel(parent=NetConfigDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=NetConfigDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lePort = QtWidgets.QLineEdit(parent=NetConfigDialog)
        self.lePort.setMaxLength(5)
        self.lePort.setObjectName("lePort")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lePort)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NetConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(NetConfigDialog)
        self.buttonBox.accepted.connect(NetConfigDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NetConfigDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NetConfigDialog)

    def retranslateUi(self, NetConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        NetConfigDialog.setWindowTitle(_translate("NetConfigDialog", "Настройки сети"))
        self.label.setText(_translate("NetConfigDialog", "Адрес"))
        self.label_2.setText(_translate("NetConfigDialog", "Порт"))
        self.lePort.setInputMask(_translate("NetConfigDialog", "d9999"))
        self.lePort.setText(_translate("NetConfigDialog", "1580"))
        self.lePort.setPlaceholderText(_translate("NetConfigDialog", "Номер порта для подключения"))
